### ISSUE TITLE
Not all esbuild options are forwarded

### ISSUE THREAD

**Issue by pip25** [hannoeru/jest-esbuild#2]
Only "loader", "format", "target", "jsxFactory", "jsxFragment" and "sourcemap" are used, the rest of the options are ignored. This could be solved simply by including a "...userOptions," line into the resolveOptions function before the above properties.

**Comment by hannoeru** [comment]
Can you make a PR for this?

**Comment by pip25** [comment]
My colleague was about to submit one, but you were faster, apparently. Thanks for the quick fix and release. :)

**Comment by httpete** [comment]
I still get: error: Invalid option in transform() call: "inject"
